name: challenge1

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Print date
              run: date
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Print date
              run: Get-Date
    job3:
        name: Third Job
        runs-on: macos-13
        steps:
            - name: Print date
              run: date
    job4:
        name: Fourth Job
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: Print success message
              run: echo "Success!"