name: challenge2

on: push

env:
  ARTIFACT_NAME: my_artifact

jobs:
    main:
        name: Checkout & Upload
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3


    job2:
        name: Upload Artifact
        runs-on: ubuntu-latest
        steps:
        - uses: actions/upload-artifact@v3
          with:
            name: ${{ env.ARTIFACT_NAME }}
            path: ./